[General]
update-url = https://cdn.jsdelivr.net/gh/xszo/etc@o/net/other/sr.conf
hijack-dns = *:53
dns-server = system

[Proxy Group]
NODE = url-test, url=http://1.1.1.1/, policy-regex-filter=.*
JP = url-test, url=http://1.1.1.1/, policy-regex-filter=(?<![a-zA-Z])((JP)|(Japan)|(Tokyo))(?![a-zA-Z])|(🇯🇵)|(?<!尼)日
TW = url-test, url=http://1.1.1.1/, policy-regex-filter=(?<![a-zA-Z])((TW)|(Taiwan))(?![a-zA-Z])|(🇹🇼)|臺|台
US = url-test, url=http://1.1.1.1/, policy-regex-filter=(?<![a-zA-Z])((US)|(NY)|(LA))(?![a-zA-Z])|(🇺🇸)|美

[Rule]
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/direct.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/global.txt, PROXY
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/system.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/block.txt, REJECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/region.txt, PROXY
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/r-cn.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/r-jp.txt, JP
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/r-tw.txt, TW
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/r-us.txt, US
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/direct.ip.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/system.ip.txt, DIRECT
GEOIP, CN, DIRECT
FINAL, PROXY
