#!/bin/zsh

ListGen=( "net/filter" "net/main" )

OptOut=false
while getopts "o" opt; do
  case ${opt} in
    o ) OptOut=true ;;
esac; done

rm -Rf tmp out
cp -Rf src out
for item in ${ListGen[@]}; do
  git checkout ${item}
  python gen.py
done

if git checkout o; then
  cp -Rf out/* .
  git add -A
  if [ ${OptOut} = true ]; then
    git commit -qm gen --amend --reset-author
    git push -f
fi; fi
rm -Rf tmp out
