[custom]
clash_rule_base=https://cdn.jsdelivr.net/gh/xszo/etc@etc/clash/conv-base+cn.yml
enable_rule_generator=false
custom_proxy_group=Node`url-test`.*`http://1.1.1.1/`600
custom_proxy_group=JP`url-test`(?<![A-Za-z])(JPN?|Japan(ese)?|Tokyo|Osaka)(?![A-Za-z])|(?<!尼)日(本|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=TW`url-test`(?<![A-Za-z])(TWN?|Taiwan(ese)?|Taipei)(?![A-Za-z])|台(灣|湾|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=US`url-test`(?<![A-Za-z])(USA?|United\s?States|American?|LA)(?![A-Za-z])|美(國|国|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
