[custom]
clash_rule_base=https://cdn.jsdelivr.net/gh/xszo/etc@etc/clash/conv-base.yml
enable_rule_generator=false
custom_proxy_group=🏳️‍🌈SYSTEM`select`[]🏳️‍🌈DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]NodeX`[]NodeS`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈DEFAULT`select`[]DIRECT`[]REJECT`[]Node0`[]Node1`[]Node2`[]Node3`[]NodeX`[]NodeS`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈R-CN`select`[]🏳️‍🌈DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]NodeX`[]NodeS`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈R-JP`select`[]🏳️‍🌈DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]NodeX`[]NodeS`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈R-TW`select`[]🏳️‍🌈DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]NodeX`[]NodeS`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈R-US`select`[]🏳️‍🌈DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]NodeX`[]NodeS`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US
custom_proxy_group=Node0`select`.
custom_proxy_group=Node1`select`.
custom_proxy_group=Node2`select`.
custom_proxy_group=Node3`select`.
custom_proxy_group=NodeX`url-test`\[X\]`http://one.one.one.one/`600
custom_proxy_group=NodeS`url-test`.`http://one.one.one.one/`600
custom_proxy_group=CN`url-test`(?<![A-Za-z])(?:CH?N|China|Shanghai)(?![A-Za-z])|中國|中国|中(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=DE`url-test`(?<![A-Za-z])(?:DEU?|Deutsch|Germany?|Berlin)(?![A-Za-z])|德國|德国|德(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=FR`url-test`(?<![A-Za-z])(?:FRA?|France|French|Paris)(?![A-Za-z])|法國|法国|法(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=GB`url-test`(?<![A-Za-z\d]|\d\s)(?:GBR?|Britain|British|UK|United\s?Kingdom|London)(?![A-Za-z])|英國|英国|英(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=HK`url-test`(?<![A-Za-z])(?:HKG?|Hong\s?Kong)(?![A-Za-z])|香港|港(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=JP`url-test`(?<![A-Za-z])(?:JPN?|Japan|Japanese|Tokyo|Osaka)(?![A-Za-z])|日本國?|(?<!尼)日(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=KR`url-test`(?<![A-Za-z])(?:KO?R|Korean?|Seoul)(?![A-Za-z])|韓國|韩国|韩(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=SG`url-test`(?<![A-Za-z])(?:SGP?|Singapore)(?![A-Za-z])|新加坡|獅城|狮城|新(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=TW`url-test`(?<![A-Za-z])(?:TWN?|Taiwan|Taiwanese|Taipei)(?![A-Za-z])|台灣|台湾|台(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
custom_proxy_group=US`url-test`(?<![A-Za-z])(?:USA?|United\s?States|American?|LA)(?![A-Za-z])|美國|美国|美(?![\u4E00-\u9FFF])`http://one.one.one.one/`600
