[custom]
clash_rule_base=https://cdn.jsdelivr.net/gh/xszo/etc@etc/clash/conv-base.yml
enable_rule_generator=false
custom_proxy_group=🚩SYSTEM`select`[]🚩DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]CN`[]DE`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US`[]Node`[]N-JMS
custom_proxy_group=🚩DEFAULT`select`[]DIRECT`[]REJECT`[]Node0`[]Node1`[]Node2`[]Node3`[]CN`[]DE`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US`[]Node`[]N-JMS
custom_proxy_group=🚩R-CN`select`[]🚩DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]CN`[]DE`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US`[]Node`[]N-JMS
custom_proxy_group=🚩R-JP`select`[]🚩DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]CN`[]DE`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US`[]Node`[]N-JMS
custom_proxy_group=🚩R-TW`select`[]🚩DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]CN`[]DE`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US`[]Node`[]N-JMS
custom_proxy_group=🚩R-US`select`[]🚩DEFAULT`[]DIRECT`[]Node0`[]Node1`[]Node2`[]Node3`[]CN`[]DE`[]GB`[]HK`[]JP`[]KR`[]SG`[]TW`[]US`[]Node`[]N-JMS
custom_proxy_group=Node0`select`.*
custom_proxy_group=Node1`select`.*
custom_proxy_group=Node2`select`.*
custom_proxy_group=Node3`select`.*
custom_proxy_group=CN`url-test`(?<![A-Za-z])(CH?N|Chin(a|ese)|Shanghai)(?![A-Za-z])|中(國|国|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=DE`url-test`(?<![A-Za-z])(DEU?|Deutsch(land)?|Germany?|Berlin)(?![A-Za-z])|德(國|国|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=GB`url-test`(?<![A-Za-z\d]|\d\s)(GBR?|Brit(ain|ish)|UK|United\s?Kingdom|London)(?![A-Za-z])|英(國|国|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=HK`url-test`(?<![A-Za-z])(HKG?|Hong\s?Kong)(?![A-Za-z])|(香?港)(\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=JP`url-test`(?<![A-Za-z])(JPN?|Japan(ese)?|Tokyo|Osaka)(?![A-Za-z])|(?<!尼)日(本|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=KR`url-test`(?<![A-Za-z])(KO?R|Korean?|Seoul)(?![A-Za-z])|(韓|韩)(國|国|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=SG`url-test`(?<![A-Za-z])(SGP?|Singapore)(?![A-Za-z])|新(加坡|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=TW`url-test`(?<![A-Za-z])(TWN?|Taiwan(ese)?|Taipei)(?![A-Za-z])|台(灣|湾|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=US`url-test`(?<![A-Za-z])(USA?|United\s?States|American?|LA)(?![A-Za-z])|美(國|国|\b|[\W\dA-Za-z])`http://1.1.1.1/`600
custom_proxy_group=Node`url-test`.*`http://1.1.1.1/`600
custom_proxy_group=N-JMS`url-test`^JMS-\d+@c\d+s\d\d?\.\w+\.[a-z]+:\d+$`http://1.1.1.1/`600
