[General]
resource-parser = https://cdn.jsdelivr.net/gh/xszo/etc@etc/network/loon-parser.js
internet-test-url = http://1.1.1.1/
proxy-test-url = http://1.1.1.1/
dns-server = 223.5.5.5, 223.6.6.6, [2400:3200::1], [2400:3200:baba::1]
doh-server = https://dns.alidns.com/dns-query

[Mitm]

[Proxy]

[Proxy Chain]

[Proxy Group]
Node = url-test, Rex0, url=http://1.1.1.1/, interval=600
JP = url-test, Rex1, url=http://1.1.1.1/, interval=600
TW = url-test, Rex2, url=http://1.1.1.1/, interval=600
US = url-test, Rex3, url=http://1.1.1.1/, interval=600

[Rule]
IP-CIDR,169.254.0.0/16,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,0.0.0.0/8,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,17.0.0.0/8,DIRECT
IP-CIDR6,::/127,DIRECT
IP-CIDR6,fe80::/10,DIRECT
IP-CIDR6,fc00::/7,DIRECT
GEOIP,CN,DIRECT
GEOIP,JP,JP
GEOIP,TW,TW
FINAL, Node

[Remote Proxy]

[Remote Filter]
Rex0 = NameRegex, FilterKey=".*"
Rex1 = NameRegex, FilterKey="(?<![A-Za-z])(JPN?|Japan(ese)?|Tokyo|Osaka)(?![A-Za-z])|(?<!尼)日(本|\b|[\W\dA-Za-z])"
Rex2 = NameRegex, FilterKey="(?<![A-Za-z])(TWN?|Taiwan(ese)?|Taipei)(?![A-Za-z])|台(灣|湾|\b|[\W\dA-Za-z])"
Rex3 = NameRegex, FilterKey="(?<![A-Za-z])(USA?|United\s?States|American?|LA)(?![A-Za-z])|美(國|国|\b|[\W\dA-Za-z])"

[Remote Rule]
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-direct.txt, tag=direct, policy=DIRECT, parser-enabled=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-system.txt, tag=system, policy=DIRECT, parser-enabled=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-world.txt, tag=world, policy=Node, parser-enabled=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-cn.txt, tag=cn, policy=DIRECT, parser-enabled=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-jp.txt, tag=jp, policy=JP, parser-enabled=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-tw.txt, tag=tw, policy=TW, parser-enabled=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-us.txt, tag=us, policy=US, parser-enabled=true, enabled=true
