[general]
profile_img_url = https://avatars.githubusercontent.com/u/97667708
resource_parser_url = https://cdn.jsdelivr.net/gh/xszo/etc@etc/network/quantumult-parser.js
network_check_url = http://1.1.1.1/
server_check_url = http://1.1.1.1/

[dns]
server = 223.5.5.5
server = 223.6.6.6
server = [2400:3200::1]
server = [2400:3200:baba::1]
doh-server = https://dns.alidns.com/dns-query

[mitm]

[policy]
url-latency-benchmark = Node, server-tag-regex=.*
url-latency-benchmark = JP, server-tag-regex=(?<![A-Za-z])(JPN?|Japan(ese)?|Tokyo|Osaka)(?![A-Za-z])|(?<!尼)日(本|\b|[\W\dA-Za-z])
url-latency-benchmark = TW, server-tag-regex=(?<![A-Za-z])(TWN?|Taiwan(ese)?|Taipei)(?![A-Za-z])|台(灣|湾|\b|[\W\dA-Za-z])
url-latency-benchmark = US, server-tag-regex=(?<![A-Za-z])(USA?|United\s?States|American?|LA)(?![A-Za-z])|美(國|国|\b|[\W\dA-Za-z])

[filter_local]
final, Node

[filter_remote]
https://cdn.jsdelivr.net/gh/xszo/etc@etc/network/quantumult-filter+cn.txt, tag=Filter, update-interval=86400, opt-parser=false, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-direct.txt, tag=Fdirect, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-system.txt, tag=Fsystem, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-world.txt, tag=Fworld, force-policy=Node, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-cn.txt, tag=Fcn, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-jp.txt, tag=Fjp, force-policy=JP, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-tw.txt, tag=Ftw, force-policy=TW, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-us.txt, tag=Fus, force-policy=US, update-interval=86400, opt-parser=true, enabled=true

[rewrite_local]

[rewrite_remote]

[server_local]

[server_remote]
