[general]
profile_img_url = https://avatars.githubusercontent.com/u/97667708
resource_parser_url = https://cdn.jsdelivr.net/gh/xszo/etc@etc/network/quantumult-parser.js
network_check_url = http://1.1.1.1/
server_check_url = http://1.1.1.1/

[dns]
server = 223.5.5.5
server = 223.6.6.6
server = [2400:3200::1]
server = [2400:3200:baba::1]
doh-server = https://dns.alidns.com/dns-query

[mitm]

[policy]
static = SYSTEM, DEFAULT, direct, Node0, Node1, Node2, Node3, CN, DE, GB, HK, JP, KR, SG, TW, US, Node, N-JMS, img-url=arrow.left.and.right.system
static = DEFAULT, direct, reject, Node0, Node1, Node2, Node3, CN, DE, GB, HK, JP, KR, SG, TW, US, Node, N-JMS, img-url=arrow.left.arrow.right.system
static = R-CN, DEFAULT, direct, Node0, Node1, Node2, Node3, CN, DE, GB, HK, JP, KR, SG, TW, US, Node, N-JMS, img-url=arrow.forward.system
static = R-JP, DEFAULT, direct, Node0, Node1, Node2, Node3, CN, DE, GB, HK, JP, KR, SG, TW, US, Node, N-JMS, img-url=arrow.forward.system
static = R-TW, DEFAULT, direct, Node0, Node1, Node2, Node3, CN, DE, GB, HK, JP, KR, SG, TW, US, Node, N-JMS, img-url=arrow.forward.system
static = R-US, DEFAULT, direct, Node0, Node1, Node2, Node3, CN, DE, GB, HK, JP, KR, SG, TW, US, Node, N-JMS, img-url=arrow.forward.system
static = Node0, server-tag-regex=.*
static = Node1, server-tag-regex=.*
static = Node2, server-tag-regex=.*
static = Node3, server-tag-regex=.*
url-latency-benchmark = CN, server-tag-regex=(?<![A-Za-z])(CH?N|Chin(a|ese)|Shanghai)(?![A-Za-z])|中(國|国|\b|[\W\dA-Za-z])
url-latency-benchmark = DE, server-tag-regex=(?<![A-Za-z])(DEU?|Deutsch(land)?|Germany?|Berlin)(?![A-Za-z])|德(國|国|\b|[\W\dA-Za-z])
url-latency-benchmark = GB, server-tag-regex=(?<![A-Za-z\d]|\d\s)(GBR?|Brit(ain|ish)|UK|United\s?Kingdom|London)(?![A-Za-z])|英(國|国|\b|[\W\dA-Za-z])
url-latency-benchmark = HK, server-tag-regex=(?<![A-Za-z])(HKG?|Hong\s?Kong)(?![A-Za-z])|(香?港)(\b|[\W\dA-Za-z])
url-latency-benchmark = JP, server-tag-regex=(?<![A-Za-z])(JPN?|Japan(ese)?|Tokyo|Osaka)(?![A-Za-z])|(?<!尼)日(本|\b|[\W\dA-Za-z])
url-latency-benchmark = KR, server-tag-regex=(?<![A-Za-z])(KO?R|Korean?|Seoul)(?![A-Za-z])|(韓|韩)(國|国|\b|[\W\dA-Za-z])
url-latency-benchmark = SG, server-tag-regex=(?<![A-Za-z])(SGP?|Singapore)(?![A-Za-z])|新(加坡|\b|[\W\dA-Za-z])
url-latency-benchmark = TW, server-tag-regex=(?<![A-Za-z])(TWN?|Taiwan(ese)?|Taipei)(?![A-Za-z])|台(灣|湾|\b|[\W\dA-Za-z])
url-latency-benchmark = US, server-tag-regex=(?<![A-Za-z])(USA?|United\s?States|American?|LA)(?![A-Za-z])|美(國|国|\b|[\W\dA-Za-z])
url-latency-benchmark = Node, server-tag-regex=.*
url-latency-benchmark = N-JMS, server-tag-regex=^JMS-\d+@c\d+s\d\d?\.\w+\.[a-z]+:\d+$

[filter_local]
final, DEFAULT

[filter_remote]
https://cdn.jsdelivr.net/gh/xszo/etc@etc/network/quantumult-filter.txt, tag=Filter, update-interval=86400, opt-parser=false, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-direct.txt, tag=Fdirect, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-system.txt, tag=Fsystem, force-policy=SYSTEM, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-world.txt, tag=Fworld, force-policy=DEFAULT, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-cn.txt, tag=Fcn, force-policy=R-CN, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-jp.txt, tag=Fjp, force-policy=R-JP, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-tw.txt, tag=Ftw, force-policy=R-TW, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-us.txt, tag=Fus, force-policy=R-US, update-interval=86400, opt-parser=true, enabled=true

[rewrite_local]

[rewrite_remote]

[server_local]

[server_remote]
