[general]
profile_img_url = https://avatars.githubusercontent.com/u/97667708
resource_parser_url = https://cdn.jsdelivr.net/gh/xszo/etc@etc/network/quantumult-parser.js
network_check_url = http://one.one.one.one/
server_check_url = http://one.one.one.one/

[dns]
server = 223.5.5.5
server = 223.6.6.6
server = [2400:3200::1]
server = [2400:3200:baba::1]
doh-server = https://dns.alidns.com/dns-query

[mitm]

[policy]
url-latency-benchmark = Node, server-tag-regex=.

[filter_local]
final, Node

[filter_remote]
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+specfi.txt, tag=DNspecfi, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+cn.txt, tag=DNcn, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+xcn.txt, tag=DNxcn, force-policy=Node, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+specfi.txt, tag=IPspecfi, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+cn.txt, tag=IPcn, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true

[rewrite_local]

[rewrite_remote]

[server_local]

[server_remote]
