[General]
update-url = https://cdn.jsdelivr.net/gh/xszo/etc@etc/network/shadowrocket+cn.conf

[Proxy Group]
Node = url-test, policy-regex-filter=.

[Rule]
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+specfi.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+cn.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+xcn.txt, Node
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+specfi.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+cn.txt, DIRECT
FINAL, Node
