[general]
network_check_url = http://1.1.1.1/
server_check_url = http://1.1.1.1/
resource_parser_url = https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/parser.js

[dns]
no-system
server = 223.5.5.5
server = 223.6.6.6
server = [2400:3200::1]
server = [2400:3200:baba::1]
doh-server = https://dns.alidns.com/dns-query

[mitm]

[policy]
static = DEFAULT, DIRECT, CN, DE, GB, HK, JP, SG, TW, US, NODE, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.arrow.right.system
static = SYSTEM, DEFAULT, DIRECT, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
static = REGION, DIRECT, CN, DE, GB, HK, JP, SG, TW, US, NODE, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.arrow.right.system
static = R-CN, REGION, DIRECT, CN, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
static = R-JP, REGION, DIRECT, JP, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
static = R-TW, REGION, DIRECT, TW, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
static = R-US, REGION, DIRECT, US, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
url-latency-benchmark = NODE, server-tag-regex=.*, img-url=arrow.triangle.swap.system
static = NODE0, server-tag-regex=.*, img-url=arrow.triangle.branch.system
static = NODE1, server-tag-regex=.*, img-url=arrow.triangle.branch.system
static = NODE2, server-tag-regex=.*, img-url=arrow.triangle.branch.system
static = NODE3, server-tag-regex=.*, img-url=arrow.triangle.branch.system
url-latency-benchmark = CN, server-tag-regex=(?<![a-zA-Z])((CN)|(CHN)|(China))(?![a-zA-Z])|中, img-url=arrow.triangle.swap.system
url-latency-benchmark = DE, server-tag-regex=(?<![a-zA-Z])((DE)|(German)|(Berlin))(?![a-zA-Z])|德, img-url=arrow.triangle.swap.system
url-latency-benchmark = GB, server-tag-regex=(?<![a-zA-Z])((?<![0-9])(GB)|(UK)|(London))(?![a-zA-Z])|英, img-url=arrow.triangle.swap.system
url-latency-benchmark = HK, server-tag-regex=(?<![a-zA-Z])((HK)|(Hong ?Kong))|港, img-url=arrow.triangle.swap.system
url-latency-benchmark = JP, server-tag-regex=(?<![a-zA-Z])((JP)|(Japan)|(Tokyo))(?![a-zA-Z])|(?<!尼)日, img-url=arrow.triangle.swap.system
url-latency-benchmark = SG, server-tag-regex=(?<![a-zA-Z])((SG)|(Singapore))(?![a-zA-Z])|新|(獅|狮城), img-url=arrow.triangle.swap.system
url-latency-benchmark = TW, server-tag-regex=(?<![a-zA-Z])((TW)|(Taiwan))(?![a-zA-Z])|台|臺, img-url=arrow.triangle.swap.system
url-latency-benchmark = US, server-tag-regex=(?<![a-zA-Z])((US)|(NY)|(LA))(?![a-zA-Z])|美, img-url=arrow.triangle.swap.system

[filter_local]
final, DEFAULT
[filter_remote]
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter.txt, update-interval=86400

[rewrite_local]
[rewrite_remote]

[server_local]
[server_remote]
