#!MANAGED-CONFIG https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/base+cn.conf interval=86400 strict=false


[General]
loglevel = warning
udp-priority = true
udp-policy-not-supported-behaviour = REJECT
allow-wifi-access = false
exclude-simple-hostnames = true
show-error-page-for-reject = true
internet-test-url = http://1.1.1.1/
proxy-test-url = http://1.1.1.1/
proxy-test-udp = one.one.one.one@1.1.1.1
hijack-dns = *:53
dns-server = 223.5.5.5, 223.6.6.6, [2400:3200::1], [2400:3200:baba::1]
encrypted-dns-server = https://dns.alidns.com/dns-query

[Proxy Group]
Node = url-test, hidden=true, include-all-proxies=true, policy-regex-filter=".*"
JP = url-test, hidden=true, include-all-proxies=true, policy-regex-filter="(?<![A-Za-z])(JPN?|Japan(ese)?|Tokyo|Osaka)(?![A-Za-z])|(?<!尼)日(本|\b|[\W\dA-Za-z])"
TW = url-test, hidden=true, include-all-proxies=true, policy-regex-filter="(?<![A-Za-z])(TWN?|Taiwan(ese)?|Taipei)(?![A-Za-z])|台(灣|湾|\b|[\W\dA-Za-z])"
US = url-test, hidden=true, include-all-proxies=true, policy-regex-filter="(?<![A-Za-z])(USA?|United\s?States|American?|LA)(?![A-Za-z])|美(國|国|\b|[\W\dA-Za-z])"

[Rule]
DOMAIN-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-direct.txt, DIRECT
DOMAIN-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-system.txt, DIRECT
DOMAIN-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-world.txt, Node
DOMAIN-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-cn.txt, DIRECT
DOMAIN-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-jp.txt, JP
DOMAIN-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-tw.txt, TW
DOMAIN-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-us.txt, US
IP-CIDR,169.254.0.0/16,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,0.0.0.0/8,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,17.0.0.0/8,DIRECT
IP-CIDR6,::/127,DIRECT
IP-CIDR6,fe80::/10,DIRECT
IP-CIDR6,fc00::/7,DIRECT
GEOIP,CN,DIRECT
GEOIP,JP,JP
GEOIP,TW,TW
FINAL, Node, dns-failed
