#!MANAGED-CONFIG https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/base.conf interval=86400 strict=false

[General]
loglevel = warning
hijack-dns = *:53
dns-server = system
internet-test-url = http://1.1.1.1/
proxy-test-url = http://1.1.1.1/

[Proxy Group]
_GLOBAL = select, DIRECT, CN, DE, GB, JP, SG, TW, US, NODE, NODE0, NODE1, NODE2, NODE3
_SYSTEM = select, _GLOBAL, DIRECT, NODE0, NODE1, NODE2, NODE3
_REGION = select, DIRECT, CN, DE, GB, JP, SG, TW, US, NODE, NODE0, NODE1, NODE2, NODE3
_CN = select, _REGION, DIRECT, CN, NODE0, NODE1, NODE2, NODE3
_JP = select, _REGION, DIRECT, JP, NODE0, NODE1, NODE2, NODE3
_TW = select, _REGION, DIRECT, TW, NODE0, NODE1, NODE2, NODE3
_US = select, _REGION, DIRECT, US, NODE0, NODE1, NODE2, NODE3

NODE0 = select, include-all-proxies=true
NODE1 = select, include-all-proxies=true
NODE2 = select, include-all-proxies=true
NODE3 = select, include-all-proxies=true

NODE = url-test, include-all-proxies=true
CN = url-test, include-all-proxies=true, policy-regex-filter=(?<![a-zA-Z])((CN)|(CHN)|(China))(?![a-zA-Z])|(🇨🇳)|中|(回国)
DE = url-test, include-all-proxies=true, policy-regex-filter=(?<![a-zA-Z])((DE)|(German)|(Berlin))(?![a-zA-Z])|(🇩🇪)|德
GB = url-test, include-all-proxies=true, policy-regex-filter=(?<![a-zA-Z])((?<![0-9]\s?)(GB)|(UK)|(London))(?![a-zA-Z])|(🇬🇧)|英
JP = url-test, include-all-proxies=true, policy-regex-filter=(?<![a-zA-Z])((JP)|(Japan)|(Tokyo))(?![a-zA-Z])|(🇯🇵)|(?<!尼)日
SG = url-test, include-all-proxies=true, policy-regex-filter=(?<![a-zA-Z])((SG)|(Singapore))(?![a-zA-Z])|(🇸🇬)|新|(獅|狮城)
TW = url-test, include-all-proxies=true, policy-regex-filter=(?<![a-zA-Z])((TW)|(Taiwan))(?![a-zA-Z])|(🇹🇼)|臺|台
US = url-test, include-all-proxies=true, policy-regex-filter=(?<![a-zA-Z])((US)|(NY)|(LA))(?![a-zA-Z])|(🇺🇸)|美

[Rule]
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/direct.txt, DIRECT, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/global.txt, _GLOBAL, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/system.txt, _SYSTEM, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/block.txt, REJECT, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/region.txt, _REGION, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/r-cn.txt, _CN, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/r-jp.txt, _JP, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/r-tw.txt, _TW, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/r-us.txt, _US, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/direct.ip.txt, DIRECT, update-interval=86400
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@o/net/surge/filter/system.ip.txt, _SYSTEM, update-interval=86400
GEOIP, CN, _CN
FINAL, _GLOBAL
