#!MANAGED-CONFIG https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/base+cn.conf interval=86400 strict=false


[General]
loglevel = warning
auto-suspend = true
ipv6 = true
udp-priority = true
udp-policy-not-supported-behaviour = REJECT
allow-wifi-access = false
exclude-simple-hostnames = true
internet-test-url = http://one.one.one.one/
proxy-test-url = http://one.one.one.one/
proxy-test-udp = one.one.one.one@1.1.1.1
hijack-dns = *:53
dns-server = 223.5.5.5, 223.6.6.6, [2400:3200::1], [2400:3200:baba::1]
encrypted-dns-server = https://dns.alidns.com/dns-query

[Proxy Group]
Node = smart, hidden=true, policy-priority="\[B\]:10;", include-all-proxies=true, policy-regex-filter="."

[Rule]
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+specfi.txt, DIRECT, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+cn.txt, DIRECT, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-dn+xcn.txt, Node, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+specfi.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/etc@etc/surge/filter-ip+cn.txt, DIRECT
FINAL, Node, dns-failed
