[general]
network_check_url = http://1.1.1.1/
server_check_url = http://1.1.1.1/
resource_parser_url = https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/parser.js

[dns]

[policy]
static = _GLOBAL, DIRECT, CN, DE, GB, JP, SG, TW, US, NODE, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.arrow.right.system
static = _SYSTEM, _GLOBAL, DIRECT, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
static = _REGION, DIRECT, CN, DE, GB, JP, SG, TW, US, NODE, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.arrow.right.system
static = _CN, _REGION, DIRECT, CN, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
static = _JP, _REGION, DIRECT, JP, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
static = _TW, _REGION, DIRECT, TW, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system
static = _US, _REGION, DIRECT, US, NODE0, NODE1, NODE2, NODE3, img-url=arrow.left.and.right.system

static = NODE0, img-url=arrow.triangle.branch.system, server-tag-regex=.*
static = NODE1, img-url=arrow.triangle.branch.system, server-tag-regex=.*
static = NODE2, img-url=arrow.triangle.branch.system, server-tag-regex=.*
static = NODE3, img-url=arrow.triangle.branch.system, server-tag-regex=.*

url-latency-benchmark = NODE, img-url=arrow.triangle.swap.system, server-tag-regex=.*
url-latency-benchmark = CN, img-url=arrow.triangle.swap.system, server-tag-regex=(?<![a-zA-Z])((CN)|(CHN)|(China))(?![a-zA-Z])|(🇨🇳)|中|(回国)
url-latency-benchmark = DE, img-url=arrow.triangle.swap.system, server-tag-regex=(?<![a-zA-Z])((DE)|(German)|(Berlin))(?![a-zA-Z])|(🇩🇪)|德
url-latency-benchmark = GB, img-url=arrow.triangle.swap.system, server-tag-regex=(?<![a-zA-Z])((?<![0-9]\s?)(GB)|(UK)|(London))(?![a-zA-Z])|(🇬🇧)|英
url-latency-benchmark = JP, img-url=arrow.triangle.swap.system, server-tag-regex=(?<![a-zA-Z])((JP)|(Japan)|(Tokyo))(?![a-zA-Z])|(🇯🇵)|(?<!尼)日
url-latency-benchmark = SG, img-url=arrow.triangle.swap.system, server-tag-regex=(?<![a-zA-Z])((SG)|(Singapore))(?![a-zA-Z])|(🇸🇬)|新|(獅|狮城)
url-latency-benchmark = TW, img-url=arrow.triangle.swap.system, server-tag-regex=(?<![a-zA-Z])((TW)|(Taiwan))(?![a-zA-Z])|(🇹🇼)|臺|台
url-latency-benchmark = US, img-url=arrow.triangle.swap.system, server-tag-regex=(?<![a-zA-Z])((US)|(NY)|(LA))(?![a-zA-Z])|(🇺🇸)|美

[filter_local]
host-suffix, quantumult.app, _GLOBAL
geoip, cn, _CN
final, _GLOBAL

[filter_remote]
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/direct.txt, tag=Direct, force-policy=DIRECT, update-interval=86400, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/global.txt, tag=Global, force-policy=_GLOBAL, update-interval=86400, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/system.txt, tag=System, force-policy=_SYSTEM, update-interval=86400, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/block.txt, tag=Block, force-policy=REJECT, update-interval=86400, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/region.txt, tag=Region, force-policy=_REGION, update-interval=86400, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/r-cn.txt, tag=R-CN, force-policy=_CN, update-interval=86400, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/r-jp.txt, tag=R-JP, force-policy=_JP, update-interval=86400, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/r-tw.txt, tag=R-TW, force-policy=_TW, update-interval=86400, enabled=true
https://cdn.jsdelivr.net/gh/xszo/etc@o/net/quantumult/filter/r-us.txt, tag=R-US, force-policy=_US, update-interval=86400, enabled=true

[mitm]

[rewrite_local]

[rewrite_remote]

[server_local]

[server_remote]
