base: https://cdn.jsdelivr.net/gh/xszo/etc@o/net/
interval: 86400
t-http: http://1.1.1.1/
dns:
  plain:
    - "1.1.1.1"
    - "1.0.0.1"
    - "[2606:4700:4700::1111]"
    - "[2606:4700:4700::1001]"
  https: https://cloudflare-dns.com/dns-query
node:
  - type: static
    name: XSZO
    content: [DIRECT]
    a-ico: checkmark.system
filter:
  - type: final
    content: DIRECT
