[custom]
clash_rule_base=https://cdn.jsdelivr.net/gh/xszo/cr/net/clash-conv-base-cn.yml
enable_rule_generator=false
custom_proxy_group=TW`url-test`(?<![A-Za-z])TWN?(?![A-Za-z])|Taiwan|Taiwanese|Taipei|台灣|台湾|台(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=JP`url-test`(?<![A-Za-z])JPN?(?![A-Za-z])|Japan|Japanese|Tokyo|Osaka|日本國?|(?<!尼)日(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=US`url-test`(?<![A-Za-z])(?:USA?|NY|LA)(?![A-Za-z])|United\s?States|American?|美國|美国|美(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
