[custom]
clash_rule_base=https://cdn.jsdelivr.net/gh/xszo/cr/net/clash-conv-base.yml
enable_rule_generator=false
custom_proxy_group=🏳️‍🌈Default`select`[]DIRECT`[]REJECT`[]Node`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]NL`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈System`select`[]🏳️‍🌈Default`[]DIRECT`[]Node`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]NL`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈R-CN`select`[]🏳️‍🌈Default`[]DIRECT`[]Node`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]NL`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈R-JP`select`[]🏳️‍🌈Default`[]DIRECT`[]Node`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]NL`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈R-TW`select`[]🏳️‍🌈Default`[]DIRECT`[]Node`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]NL`[]SG`[]TW`[]US
custom_proxy_group=🏳️‍🌈R-US`select`[]🏳️‍🌈Default`[]DIRECT`[]Node`[]CN`[]DE`[]FR`[]GB`[]HK`[]JP`[]KR`[]NL`[]SG`[]TW`[]US
custom_proxy_group=Node`url-test`^`http://1.1.1.1/`600
custom_proxy_group=CN`url-test`(?<![A-Za-z])CH?N(?![A-Za-z])|China|Shenzhen|Shanghai|中國|中国|中(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=DE`url-test`(?<![A-Za-z])DEU?(?![A-Za-z])|Deutsch|Germany?|Berlin|德國|德国|德(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=FR`url-test`(?<![A-Za-z])FRA?(?![A-Za-z])|France|French|Paris|法國|法国|法(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=GB`url-test`(?<![A-Za-z\d]|\d\s)(?:GBR?|UK)(?![A-Za-z])|Britain|British|United\s?Kingdom|London|英國|英国|英(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=HK`url-test`(?<![A-Za-z])HKG?(?![A-Za-z])|Hong\s?Kong|香港|港(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=JP`url-test`(?<![A-Za-z])JPN?(?![A-Za-z])|Japan|Japanese|Tokyo|Osaka|日本國?|(?<!尼)日(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=KR`url-test`(?<![A-Za-z])KO?R(?![A-Za-z])|Korean?|Seoul|韓國|韩国|韩(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=NL`url-test`(?<![A-Za-z])NLD?(?![A-Za-z])|Netherlands|Holland|Amsterdam|荷蘭|荷兰|荷(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=SG`url-test`(?<![A-Za-z])SGP?(?![A-Za-z])|Singapore|新加坡|獅城|狮城|新(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=TW`url-test`(?<![A-Za-z])TWN?(?![A-Za-z])|Taiwan|Taiwanese|Taipei|台灣|台湾|台(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
custom_proxy_group=US`url-test`(?<![A-Za-z])(?:USA?|NY|LA)(?![A-Za-z])|United\s?States|American?|美國|美国|美(?![\u4E00-\u9FFF])`http://1.1.1.1/`600
