[custom]
custom_proxy_group=ON`select`[]DIRECT`[]REJECT
enable_rule_generator=true
overwrite_original_rules=true
ruleset=DIRECT,[]FINAL
rename=^JMS-(\d+)@c(\d+)s1\..*@C$2S1 US $1
rename=^JMS-(\d+)@c(\d+)s2\..*@C$2S2 US $1
rename=^JMS-(\d+)@c(\d+)s3\..*@C$2S3 US $1
rename=^JMS-(\d+)@c(\d+)s4\..*@C$2S4 JP $1
rename=^JMS-(\d+)@c(\d+)s5\..*@C$2S5 NL $1
rename=^JMS-(\d+)@c(\d+)s(\d+)\..*@C$2S$3 $1
add_emoji=true
remove_old_emoji=false
clash_rule_base=https://cdn.jsdelivr.net/gh/xszo/cr/null
surge_rule_base=https://cdn.jsdelivr.net/gh/xszo/cr/null
