[general]
resource_parser_url = https://cdn.jsdelivr.net/gh/xszo/cr/net/quantumult-parser.js
network_check_url = http://1.1.1.1/
server_check_url = http://1.1.1.1/

[dns]
server = 223.5.5.5
server = 223.6.6.6
doh-server = https://223.5.5.5/dns-query, https://223.6.6.6/dns-query, https://doh.pub/dns-query

[mitm]

[policy]
url-latency-benchmark = TW, server-tag-regex=(?<![A-Za-z])TWN?(?![A-Za-z])|Taiwan|Taiwanese|Taipei|台灣|台湾|台(?![\u4E00-\u9FFF])
url-latency-benchmark = JP, server-tag-regex=(?<![A-Za-z])JPN?(?![A-Za-z])|Japan|Japanese|Tokyo|Osaka|日本國?|(?<!尼)日(?![\u4E00-\u9FFF])
url-latency-benchmark = US, server-tag-regex=(?<![A-Za-z])(?:USA?|NY|LA)(?![A-Za-z])|United\s?States|American?|美國|美国|美(?![\u4E00-\u9FFF])

[filter_local]
final, US

[filter_remote]
https://cdn.jsdelivr.net/gh/xszo/cr/rule/system-dn-s.txt, tag=DNsystem, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/cn-dn-s.txt, tag=DNcn, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/tw-dn-s.txt, tag=DNtw, force-policy=TW, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/jp-dn-s.txt, tag=DNjp, force-policy=JP, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/us-dn-s.txt, tag=DNus, force-policy=US, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/world-dn-s.txt, tag=DNworld, force-policy=US, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/system-ip-s.txt, tag=IPsystem, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/cn-ip-s.txt, tag=IPcn, force-policy=direct, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/tw-ip-s.txt, tag=IPtw, force-policy=TW, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/jp-ip-s.txt, tag=IPjp, force-policy=JP, update-interval=86400, opt-parser=true, enabled=true
https://cdn.jsdelivr.net/gh/xszo/cr/rule/world-ip-s.txt, tag=IPworld, force-policy=US, update-interval=86400, opt-parser=true, enabled=true

[rewrite_local]

[rewrite_remote]

[server_local]

[server_remote]
