[General]
update-url = https://cdn.jsdelivr.net/gh/xszo/cr/net/shadowrocket-cn.conf

[Proxy Group]
TW = url-test, policy-regex-filter=(?<![A-Za-z])TWN?(?![A-Za-z])|Taiwan|Taiwanese|Taipei|台灣|台湾|台(?![\u4E00-\u9FFF])
JP = url-test, policy-regex-filter=(?<![A-Za-z])JPN?(?![A-Za-z])|Japan|Japanese|Tokyo|Osaka|日本國?|(?<!尼)日(?![\u4E00-\u9FFF])
US = url-test, policy-regex-filter=(?<![A-Za-z])(?:USA?|NY|LA)(?![A-Za-z])|United\s?States|American?|美國|美国|美(?![\u4E00-\u9FFF])

[Rule]
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/system-dn-s.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/cn-dn-s.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/tw-dn-s.txt, TW
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/jp-dn-s.txt, JP
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/us-dn-s.txt, US
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/world-dn-s.txt, US
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/system-ip-s.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/cn-ip-s.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/tw-ip-s.txt, TW
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/jp-ip-s.txt, JP
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/world-ip-s.txt, US
FINAL, US
