#!MANAGED-CONFIG https://cdn.jsdelivr.net/gh/xszo/cr/net/surge-base.conf interval=86400 strict=false


[General]
internet-test-url = http://1.1.1.1/
proxy-test-url = http://1.1.1.1/
proxy-test-udp = one.one@1.1.1.1
hijack-dns = *:53
dns-server = system, 223.5.5.5, 223.6.6.6
encrypted-dns-server = https://223.5.5.5/dns-query, https://223.6.6.6/dns-query, https://doh.pub/dns-query

[Proxy Group]
Default = select, DIRECT, REJECT, Node, CN, DE, FR, GB, HK, JP, KR, NL, SG, TW, US
System = select, Default, DIRECT, Node, CN, DE, FR, GB, HK, JP, KR, NL, SG, TW, US
R-CN = select, Default, DIRECT, Node, CN, DE, FR, GB, HK, JP, KR, NL, SG, TW, US
R-JP = select, Default, DIRECT, Node, CN, DE, FR, GB, HK, JP, KR, NL, SG, TW, US
R-TW = select, Default, DIRECT, Node, CN, DE, FR, GB, HK, JP, KR, NL, SG, TW, US
R-US = select, Default, DIRECT, Node, CN, DE, FR, GB, HK, JP, KR, NL, SG, TW, US
Node = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="^"
CN = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])CH?N(?![A-Za-z])|China|Shenzhen|Shanghai|中國|中国|中(?![\u4E00-\u9FFF])"
DE = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])DEU?(?![A-Za-z])|Deutsch|Germany?|Berlin|德國|德国|德(?![\u4E00-\u9FFF])"
FR = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])FRA?(?![A-Za-z])|France|French|Paris|法國|法国|法(?![\u4E00-\u9FFF])"
GB = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z\d]|\d\s)(?:GBR?|UK)(?![A-Za-z])|Britain|British|United\s?Kingdom|London|英國|英国|英(?![\u4E00-\u9FFF])"
HK = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])HKG?(?![A-Za-z])|Hong\s?Kong|香港|港(?![\u4E00-\u9FFF])"
JP = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])JPN?(?![A-Za-z])|Japan|Japanese|Tokyo|Osaka|日本國?|(?<!尼)日(?![\u4E00-\u9FFF])"
KR = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])KO?R(?![A-Za-z])|Korean?|Seoul|韓國|韩国|韩(?![\u4E00-\u9FFF])"
NL = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])NLD?(?![A-Za-z])|Netherlands|Holland|Amsterdam|荷蘭|荷兰|荷(?![\u4E00-\u9FFF])"
SG = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])SGP?(?![A-Za-z])|Singapore|新加坡|獅城|狮城|新(?![\u4E00-\u9FFF])"
TW = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])TWN?(?![A-Za-z])|Taiwan|Taiwanese|Taipei|台灣|台湾|台(?![\u4E00-\u9FFF])"
US = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])(?:USA?|NY|LA)(?![A-Za-z])|United\s?States|American?|美國|美国|美(?![\u4E00-\u9FFF])"

[Rule]
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/system-dn-s.txt, System, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/cn-dn-s.txt, R-CN, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/jp-dn-s.txt, R-JP, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/tw-dn-s.txt, R-TW, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/us-dn-s.txt, R-US, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/world-dn-s.txt, Default, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/system-ip-s.txt, System
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/cn-ip-s.txt, R-CN
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/jp-ip-s.txt, R-JP
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/tw-ip-s.txt, R-TW
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/world-ip-s.txt, Default
FINAL, Default, dns-failed
