#!MANAGED-CONFIG https://cdn.jsdelivr.net/gh/xszo/cr/net/surge-base-cn.conf interval=86400 strict=false


[General]
internet-test-url = http://1.1.1.1/
proxy-test-url = http://1.1.1.1/
proxy-test-udp = one.one@1.1.1.1
hijack-dns = *:53
dns-server = system, 223.5.5.5, 223.6.6.6
encrypted-dns-server = https://223.5.5.5/dns-query, https://223.6.6.6/dns-query, https://doh.pub/dns-query

[Proxy Group]
TW = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])TWN?(?![A-Za-z])|Taiwan|Taiwanese|Taipei|台灣|台湾|台(?![\u4E00-\u9FFF])"
JP = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])JPN?(?![A-Za-z])|Japan|Japanese|Tokyo|Osaka|日本國?|(?<!尼)日(?![\u4E00-\u9FFF])"
US = smart, include-all-proxies=true, include-other-group=Proxy, policy-regex-filter="(?<![A-Za-z])(?:USA?|NY|LA)(?![A-Za-z])|United\s?States|American?|美國|美国|美(?![\u4E00-\u9FFF])"

[Rule]
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/system-dn-s.txt, DIRECT, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/cn-dn-s.txt, DIRECT, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/tw-dn-s.txt, TW, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/jp-dn-s.txt, JP, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/us-dn-s.txt, US, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/world-dn-s.txt, US, no-resolve, extended-matching
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/system-ip-s.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/cn-ip-s.txt, DIRECT
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/tw-ip-s.txt, TW
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/jp-ip-s.txt, JP
RULE-SET, https://cdn.jsdelivr.net/gh/xszo/cr/rule/world-ip-s.txt, US
FINAL, US, dns-failed
